### ISSUE TITLE
Issue with rate_code_dim df

### ISSUE THREAD

**Issue by minalfrancis** [darshilparmar/uber-etl-pipeline-data-engineering-project#1]
Hi Darshil.

I'm following your uber data analysis project and I'm facing an issue with the rate_code_dim df. After following the instructions given by you, the RatecodeID and the rate_code_id columns values are getting to be different. Can you please help me with this issue?
![Screenshot (54)](https://github.com/darshilparmar/uber-etl-pipeline-data-engineering-project/assets/121748391/08ddf2d1-92a1-49bf-b468-0ef651bb5b11)

**Comment by darshilparmar** [comment]
You need to convert `rate_code_id` into type int
